apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o3o66wij7-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:46b47a3b8084093cba0aa723d296f42c178f6bb5@sha256:2ef9d7cfda88f42d1b0e872ccb5ea520803803fa11a18341e9d710d6d1b7ac67
          name: container-image
