apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o3o66wij7-dotnet-basic
  janus-idp.io/tekton: o3o66wij7-dotnet-basic
  backstage.io/kubernetes-id: o3o66wij7-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o3o66wij7-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
